### ISSUE TITLE
method_missing no longer supported in Chef 13

### ISSUE THREAD

**Issue by rjlee** [sometimesfood/chef-apt-repo#11]
apt-repo relies on method_missing:

```
       NoMethodError
       -------------
       private method `method_missing' called for cookbook: server_base, recipe: go :Chef::Recipe

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/apt-repo/libraries/apt-repo.rb:7:in `rescue in dont_clone_resource'
         /tmp/kitchen/cache/cookbooks/apt-repo/libraries/apt-repo.rb:3:in `dont_clone_resource'
         /tmp/kitchen/cache/cookbooks/apt-repo/definitions/apt-repo.rb:41:in `block in from_file'
         /tmp/kitchen/cache/cookbooks/apt-repo/definitions/ppa.rb:33:in `block in from_file'
         /tmp/kitchen/cache/cookbooks/server_base/recipes/go.rb:3:in `from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/apt-repo/libraries/apt-repo.rb:

         1:  module AptRepo
         2:    # ugly hack to prevent resource cloning
         3:    def self.dont_clone_resource(recipe, resource_type, resource_name, &block)
         4:      recipe.resources(resource_type => resource_name)
         5:    rescue Chef::Exceptions::ResourceNotFound
         6:      # Chef uses method missing magic
         7>>     recipe.method_missing(resource_type, resource_name, &block)
         8:    end
         9:  end
        10:

       System Info:
       ------------
       chef_version=13.7.16
       platform=ubuntu
       platform_version=16.04
       ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
       program_name=chef-client worker: ppid=97;start=20:48:50;
       executable=/opt/chef/bin/chef-client
```

This is now removed from Chef 13 and apt-repo no longer works with the latest versions of Chef - https://github.com/chef/chef-rfc/blob/master/rfc052-missing-method-missing.md

**Comment by sometimesfood** [comment]
Thanks for the bug report, @rjlee.

I am not currently using Chef for any projects, so I will have to look into this.

**Comment by sometimesfood** [comment]
@rjlee Could you give the latest master branch a shot?

In the long run you might be better off using the official apt cookbook. I stopped using Chef myself quite some time ago, which is why I have not updated this project for so long.
